### ISSUE TITLE
Is it OK to add helm-mu to MELPA?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm-mu#14]
I made a PR https://github.com/milkypostman/melpa/pull/2793

**Comment by tmalsburg** [comment]
Well there was a reason why I didn't put it up on Melpa.  There is a bug in the interaction of helm-mu and mu4e.  This can cause you to reply to an incorrect email without noticing it or attachments may not open.  The problem is that fixing this bug may require a bigger change in mu4e and since the bug isn't triggered within mu4e, the maintainer has probably no interest in fixing it.  The problem is `helm-mu-display-email` works but when you reply, forward the email, or when try to open its attachments, mu4e doesn't use the displayed message but the message that is selected in head-view.

**Comment by xuchunyang** [comment]
I have just noticed the bug, I think It is necessary to let user know it and helm-mu is still very useful for just searching mails & contacts.

**Comment by tmalsburg** [comment]
Yay, I found the trigger of the bug and added a workaround in 6443ead5cfc72bad93f5f0ee600c3ded611172a5.  Could you please confirm that it works now?  If yes, feel free to reopen your PR on MELPA.

**Comment by xuchunyang** [comment]
Yes, of course.

**Comment by tmalsburg** [comment]
Thank you!

**Comment by xuchunyang** [comment]
Looks good to me.
