### ISSUE TITLE
Adding implicit wildcards to search queries

### ISSUE THREAD

**Issue by iqbalansari** [emacs-helm/helm-mu#28]
Right now while searching for mails I have to enter complete words to get any results. I realize that `*` can be added to query for prefix search but I find it a bit inconvenient, since I have to remember to add the wildcard. I was wondering whether you would be open to adding a customization for adding implicit wildcards to search queries.

I am proposing that before passing the user input query to `mu`  we append `*` to query. I think this would make `helm-mu` feel more like an incremental search, since results we would be getting results immediately instead of waiting for the user enter a complete word. I have implemented this in a [separate branch](https://github.com/iqbalansari/helm-mu/tree/feature/implicit-wildcard) and have been using it for a week now and am finding it very convenient.

**Comment by tmalsburg** [comment]
I didn't know about the `*` operator, very useful.  I'll look at your code and will try it.

**Comment by tmalsburg** [comment]
Some comments (a little nit-picky, I admit):

1.) In the code you say: "Do not insert a wildcard if we the pattern is ending at a non-word character"  Could you give me a situation where this applies and briefly explain why we need this?

2.) Why do you pass `helm-pattern` to the function `helm-mu-get-search-pattern`?

3.) Why is `helm-mu-append-implicit-wildcard-p` a function?  This is only used in `helm-mu-get-search-pattern` and I can't imagine another use case.

4.) Could you please end the sentence-final period to the docstring of the new variable?  A sentence explaining what the wildcard does would also be great.

**Comment by iqbalansari** [comment]
Thanks for your feedback. I agree that the feature needs to better documented, its just that I did not want to spend much time on it without knowing whether you are interested in merging this. 

> In the code you say: "Do not insert a wildcard if we the pattern is ending at a non-word character" Could you give me a situation where this applies and briefly explain why we need this?

Since we always append a `*` at the end, it makes it impossible to exact matches (which can be useful at times), so I thought that if user quotes a term (eg. "git") we would not append the wildcard to it, making it possible to make exact match searches. A `*` after a space is meaningless since xapian does not support leading wildcards, lastly a `*` followed by other `*` would be meaningless. [Earlier](https://github.com/iqbalansari/helm-mu/blob/f06f782cf2c816fa9b597752433dc78a6f55960f/helm-mu.el#L210-L214) I was checking only for these characters but then I thought it would be better to be more restrictive and append wildcards only at places we know for sure it makes sense.

> Why do you pass helm-pattern to the function helm-mu-get-search-pattern?

That is to avoid depending on a global variable.

> Why is helm-mu-append-implicit-wildcard-p a function? It is only used in helm-mu-get-search-pattern and I can't imagine another use case.

There is one case we might need it (I have not coded it up yet). Suppose user enters `git` so he gets all emails from `git*` now if she wants to restrict this to emails about `helm-mu`, so he would enter <kbd>SPC</kbd><kbd>h</kbd><kbd>e</kbd><kbd>l</kbd><kbd>m</kbd><kbd>-</kbd><kbd>m</kbd> but this would not yet any results since now the pattern sent to `mu` would be `git helm-m*` this I think would be unintuitive and potentially annoying. 

I was thinking this could be fixed by rebinding <kbd>SPC</kbd> to a command that inserts `* ` (wildcard followed by a space) instead of just a single space. So if user presses a <kbd>SPC</kbd> after entering `git` the input is changed to `git* `, that way query sent to `mu` in the previous example would be `git* helm-m*` which  would work as expected.

> Could you please end the sentence-final period to the docstring of the new variable? A sentence explaining what the wildcard does would also be great.

Completely agree with you here. As I said I wanted to know whether you are interested in the feature, before spending more time on it. Let me know if you agree with the above and I will cleanup the code/documentation and open a pull request.

**Comment by tmalsburg** [comment]
It *is* possible to search for exact matches.  Just enter a space after the word, for example enter `nation ` (there is a space after *nation*) to search for *nation* but not *national*.  It seems that a `*` following a space has no effect at all, so we can drop the additional condition on appending stars.

Regarding `helm-pattern`, we depend on the global variable anyway, just at a different point in the code.  So there is no harm in dropping the `pattern` parameter from `helm-mu-get-search-pattern`.  In general, use of global variables is considered more acceptable in Emacs than otherwise.  It falls out from the design of Emacs and can often not easily be avoided.

> Suppose user enters git so she gets all emails matching git* now if she wants to restrict this to emails about helm-mu she would enter SPChelm-m but this would not yet any results since now the pattern sent to mu would be git helm-m*. This I think would be unintuitive and potentially annoying.

I don't think this is a problem.  The user first enters `git` which means that `git*` is sent to mu.  Before the user can enter `helm-mu`, they have to enter a space and that basically gets rid of the star following `git`.  So I don't think the behaviour would be counterintuitive.  If the user wants to search for all emails containing words starting with `git` and word starting with `helm-m`, they have to enter `git* helm-m`.  I would not want to bind space such that it inserts a `*` because then it really is difficult to search for exact matches.

**Comment by tmalsburg** [comment]
Other than that, I think this is a really great addition and would like to include it.  Thank you!
