### ISSUE TITLE
helm-mu-contacts cannot find contacts

### ISSUE THREAD

**Issue by tollerm** [emacs-helm/helm-mu#55]
The last version of mu has no option --after when searching contacts. Therefore, function (helm-mu-contacts-init) returns an empty list. To fix this problem, the option --format json should be used and then returned JSON records which have 'last-seen' fields can be filtered using jq tool.
Best regards,
Toller

**Comment by tmalsburg** [comment]
Thank you. I noticed that helm-mu-contacts isn't working but I didn't have time to investigate.  Gotta say, I'm surprised that `--after` was removed because it was pretty useful.  Now, mu will create a ton of Json only for it to be discarded later on.  Seems wasteful.  I think I will simply remove the after-feature.  Switching to Json format and adding a dependency to jq just for this feature doesn't seem justified.

**Comment by tmalsburg** [comment]
See here: https://github.com/djcb/mu/issues/2470

**Comment by tmalsburg** [comment]
Should be fixed with the latest version of mu (where `--after` is restored now).

**Comment by tollerm** [comment]
Thank you (and Dirk-Jan) for the prompt fix! There is a small non-important glitch though. It does not work with default
time "01-Jan-1970 00:00:00".  With this time mu gives error message that value 0 is not in range 2.22e-308 to 1.79e308. Taking into account that difference in 1 sec is not important changing default time to "01-Jan-1970 00:00:01" fixes this problem.

**Comment by tmalsburg** [comment]
Fixed. Thank you.
